/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

sourceSets {
    main {
        java {
            srcDirs ("src/com/java/", "src/com/java/root/") // Add your subfolder here
        }
    }
}

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    kotlin("jvm") version "1.9.23"
    id ("org.openjfx.javafxplugin") version "0.0.10"
}
javafx{
    version = "15"
    modules = listOf( "javafx.controls", "javafx.fxml", "javafx.graphics" )
}
repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation file("C:\\JDK\\javafx-sdk-22\\lib")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "src.com.java.root.App"
}
