/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

sourceSets {
    main {
        java {
            srcDirs ("src/com/java/", "src/com/java/root/") 
        }       
    }

}

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    kotlin("jvm") version "1.9.23"
    id ("org.openjfx.javafxplugin") version "0.0.10"
}
javafx{
    version = "15"
    modules = listOf( "javafx.controls", "javafx.fxml", "javafx.graphics" )
}
repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation(kotlin("stdlib-jdk8"))
    implementation("org.openjfx:javafx-controls:15.0.1")
    implementation("org.openjfx:javafx-fxml:15.0.1")
    implementation("org.openjfx:javafx-base:15.0.1")
    implementation("org.openjfx:javafx-graphics:15.0.1")
    implementation("org.openjfx:javafx-media:15.0.1")
    implementation("org.openjfx:javafx-swing:15.0.1")
    implementation("org.openjfx:javafx-web:15.0.1")

    //implementationFiles("C:\\JDK\\javafx-sdk-22\\lib")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "src.com.java.root.App"
}

/* 
tasks {
    compileKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
    compileTestKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }

    named("run").configure {
        if (project.hasProperty("mainClass")) {
            val mainClass: String by project
            systemProperty("java.awt.headless", "true")
            args("--module-path", "C:\\JDK\\javafx-sdk-22\\lib", "--add-modules", "javafx.controls,javafx.fxml", mainClass)
        }
    }
} */
