/* DO NOT EDIT THIS FILE - it is machine generated */
#include <C:\JDK\jdk-22\include\jni.h>
/* Header for class com_java_NativeInterface */

#ifndef _Included_com_java_NativeInterface
#define _Included_com_java_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java_NativeInterface
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_java_NativeInterface_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
